name: mp4 Transcode discord
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'mp4 file URL'
        required: true
      
      name:
        description: 'mp4 file name'
        required: true
        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y ffmpeg wget
      - run: |
          wget https://github.com/subekti404dev/hls-converter-action/releases/download/v1/dcwh
          mv dcwh /usr/local/bin/
          chmod +x /usr/local/bin/dcwh
      - run: wget -O  ${{ github.event.inputs.name }}.mp4 ${{ github.event.inputs.url }}
      - run: ls -lah
      - run: "ffmpeg -i  ${{ github.event.inputs.name }}.mp4 -codec: copy -start_number 0 -hls_time 10 -hls_list_size 0 -f hls  ${{ github.event.inputs.name }}.m3u8"
      - run: ls -lah
      - run: |
          dcwh "${{ secrets.DISCORD_WEBHOOK_URL }}"
