name: mp4 Transcode
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'mp4 file URL'
        required: true
      
      name:
        description: 'mp4 file name'
        required: true
        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y ffmpeg wget
      - run: wget -O  ${{ github.event.inputs.name }}.mp4 ${{ github.event.inputs.url }}
      - run: ls -lah
      - run: "ffmpeg -i  ${{ github.event.inputs.name }}.mp4 -codec: copy -start_number 0 -hls_time 10 -hls_list_size 0 -f hls  ${{ github.event.inputs.name }}.m3u8"
      - run: ls -lah
      - run: |
          bot_token="${{ secrets.TG_BOT_TOKEN }}"
          chat_id="${{ secrets.TG_CHAT_ID }}"
          folder_path="./"
          m3u8_file="${{ github.event.inputs.name }}.m3u8"
          
          # Upload each .ts file
          for ts_file in "${folder_path}"*.ts; do
              file_id=$(curl -s --location "https://api.telegram.org/bot${bot_token}/sendDocument" \
                  --form "chat_id=${chat_id}" \
                  --form "document=@\"${ts_file}\"" | jq -r '.result.document.file_id')
          
              # Generate direct link
              direct_link="https://telefile-proxy.uripsub.dev/file/${file_id}"
          
              # Replace .ts file name with direct link in the .m3u8 file
              sed -i "s|$(basename "${ts_file}")|${direct_link}|g" "${m3u8_file}"
          done
          
          echo "Upload and link replacement completed."
          
      - run: |
          bot_token="${{ secrets.TG_BOT_TOKEN }}"
          chat_id="${{ secrets.TG_CHAT_ID }}"
          m3u8_file="${{ github.event.inputs.name }}.m3u8"
          
          file_id=$(curl -s --location "https://api.telegram.org/bot${bot_token}/sendDocument" \
                  --form "chat_id=${chat_id}" \
                  --form "document=@\"${m3u8_file}\"" | jq -r '.result.document.file_id')
          
          # Generate direct link
          direct_link="https://telefile-proxy.uripsub.dev/file/${file_id}"
      
          echo "${direct_link}"        
