name: mp4 Transcode
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'mp4 file URL'
        required: true
      
      name:
        description: 'mp4 file name'
        required: true
        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y ffmpeg wget
      - run: wget -O  ${{ github.event.inputs.name }}.mp4 ${{ github.event.inputs.url }}
      - run: ls -lah
      - run: "ffmpeg -i  ${{ github.event.inputs.name }}.mp4 -codec: copy -start_number 0 -hls_time 10 -hls_list_size 0 -f hls  ${{ github.event.inputs.name }}.m3u8"
      - run: ls -lah
      - run: |
          m3u8_file=$(find "./" -maxdepth 1 -type f -name '*.m3u8')
          echo "$m3u8_file"
          cat "$m3u8_file"
          
